FROM openjdk:8-alpine

MAINTAINER Burgaud Valentin "xharos@islandswars.fr"
MAINTAINER TheElectronWill "theelectronwill@gmail.com"

WORKDIR /server
ADD build/libs/tuubes-full-core.jar tuubes-full-core.jar
ADD init.sh init.sh
RUN chmod +x init.sh

ENV JVM_OPTS -Xmx1024M -Xms1024M

EXPOSE 25565

CMD ["sh", "./init.sh"]